name: pytorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - python=3
  - scipy
  - scikit-learn
  - pytorch::pytorch
  - pytorch::torchvision
  - pip
- pip:
    - watermark
    - nbgitpuller
    - sphinx-gallery
