name: pytorch-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - numpy
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - matplotlib
  - pandas
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
